query User($username: String!) {
    user(username: $username) {
        favorites {
            favorites {
                song {
                    id
                }
            }
        }
    }
}
